/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Payam Tavakoli (https://sketchfab.com/payamtavakoli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-monitor-37a0fbbf74cd41bdb91c37156954d7c1
Title: Sci fi Monitor
*/

import React, { useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';

export function MonitorBener(props) {
  const { nodes, materials } = useGLTF('models/sci_fi_monitor.glb');

  const monitortxt = useTexture('textures/desk/monitor.png');
  const screenTxt = useTexture('textures/desk/screen.png');

  return (
    <group {...props} dispose={null}>
      <group rotation={[-5, 6.3, 3.45]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Material.005']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials['Material.010']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['Material.012']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.None} />
        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Material.011']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials['Material.018']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Material.019']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials['Material.014']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials['Material.013']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials['Material.015']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials['Material.016']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials['Material.017']}></mesh>
        <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials['Material.002']}>
          <meshMatcapMaterial map={monitortxt} />;
          <meshMatcapMaterial map={screenTxt} />;
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('/models/sci_fi_monitor.glb');
